services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_DB: scraper_db
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data: